#! /bin/bash

clear

wlan1ip=$(ifconfig | grep -A 1 'wlan1' | tail -1 | cut -d ' ' -f 10)
scriptdir=~/tripmaster/script

wlan1_up() {
    while [[ "$wlan1ip" != "192.168."* ]]
    do
         # clear
         echo "Checke wlan1 IP...$wlan1ip"
         wlan1ip=$(ifconfig | grep -A 1 'wlan1' | tail -1 | cut -d ' ' -f 10)
         sleep 2
         
         if [[ "$wlan1ip" = "169.254."* ]]
         then
            sudo ifconfig wlan1 down
            sleep 2
            sudo ifconfig wlan1 up
            sleep 2
         fi
    done
}

while [ 1 ]
do
#                                              H  B  Listenhöhe
CHOICE=$(
whiptail --title "Tripmaster Steuerung" --menu "" 13 50 6 \
    "1)" "Starte Tripmaster DEBUG" \
    "2)" "Starte Tripmaster" \
    "3)" "Stoppe Tripmaster" \
    "4)" "Verfolge Tripmaster LOG" \
    "5)" "Verfolge Tripmaster ERR" \
    "6)" "Full System Upgrade" \
    3>&2 2>&1 1>&3
)

case $CHOICE in
    "1)")
        trap $scriptdir/start_tripmaster_debug.sh EXIT
    ;;
    "2)")
        trap $scriptdir/start_tripmaster.sh EXIT
    ;;
    "3)")
        trap $scriptdir/kill_tripmaster.sh EXIT
    ;;
    "4)")
        trap $scriptdir/tripmaster_log.sh EXIT
    ;;
    "5)")
        trap $scriptdir/tripmaster_err.sh EXIT
    ;;
    "6)")
         wlan1_up
         clear
         if (whiptail --title "Update" --yesno "Full System Upgrade?" 8 40)
         then
            sudo sync \
            && echo -e "\e[1;32m\nFull System Upgrade\e[0m" \
            && echo -e "\e[36m\n    update...\n\e[0m" && sudo apt update \
            && echo -e "\e[36m\n    full-upgrade...\n\e[0m" && sudo apt full-upgrade -y \
            && echo -e "\e[36m\n    autoremove...\n\e[0m" && sudo apt autoremove -y --purge \
            && echo -e "\e[36m\n    autoclean...\n\e[0m" && sudo apt autoclean \
            && echo -e "\e[1;32m\nDone.\n\e[0m" \
            && sudo sync;
        fi
    ;;
esac
exit
done
